# Generated by Django 2.2.5 on 2019-10-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Slider'},
        ),
    ]
