# Generated by Django 2.2.5 on 2019-11-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_photography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographpf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='Photographpf')),
            ],
        ),
        migrations.DeleteModel(
            name='photography',
        ),
    ]
