# Generated by Django 2.2.5 on 2019-11-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20191114_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photographpf',
            options={'verbose_name_plural': 'Photographpf'},
        ),
    ]
