# Generated by Django 2.2.5 on 2019-11-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_author_blog_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(max_length=200),
        ),
    ]
