# Generated by Django 2.2.5 on 2019-11-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20191116_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateTimeField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(max_length=200, unique=True),
        ),
    ]
