# Generated by Django 2.2.5 on 2019-11-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20191116_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Cosmos',
        ),
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category'),
        ),
    ]
